version: '3.8'
services:
  reactjs:
    container_name: swafe-landing-page-front
    image: 'node:latest'
    working_dir: /home/reactjs/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm i && npm start'
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/reactjs/app'
